// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Models.Configurations
{
    public partial class categoriesConfiguration : IEntityTypeConfiguration<categories>
    {
        public void Configure(EntityTypeBuilder<categories> entity)
        {
            entity.HasKey(e => e.category_code)
                .HasName("PK__categori__BC9D1E7D454E3612");

            entity.Property(e => e.category_name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<categories> entity);
    }
}
