// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Models.Configurations
{
    public partial class price_historyConfiguration : IEntityTypeConfiguration<price_history>
    {
        public void Configure(EntityTypeBuilder<price_history> entity)
        {
            entity.HasKey(e => e.history_id)
                .HasName("PK__price_hi__096AA2E9851FD57A");

            entity.Property(e => e.change_date)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.toy_codeNavigation)
                .WithMany(p => p.price_history)
                .HasForeignKey(d => d.toy_code)
                .HasConstraintName("FK__price_his__toy_c__49C3F6B7");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<price_history> entity);
    }
}
