// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Data.Models.Configurations
{
    public partial class toysConfiguration : IEntityTypeConfiguration<toys>
    {
        public void Configure(EntityTypeBuilder<toys> entity)
        {
            entity.HasKey(e => e.code)
                .HasName("PK__toys__357D4CF8DA8F0ABA");

            entity.Property(e => e.code).ValueGeneratedNever();

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.category)
                .WithMany(p => p.toys)
                .HasForeignKey(d => d.category_id)
                .HasConstraintName("FK__toys__category_i__3E52440B");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<toys> entity);
    }
}
