// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class orders
    {
        public orders()
        {
            order_line = new HashSet<order_line>();
        }

        public int order_id { get; set; }
        public int? client_id { get; set; }
        public decimal total_amount { get; set; }
        public DateTime order_date { get; set; }
        public bool? state { get; set; }

        public virtual users client { get; set; }
        public virtual ICollection<order_line> order_line { get; set; }
    }
}