// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class price_history
    {
        public int history_id { get; set; }
        public int? toy_code { get; set; }
        public decimal price { get; set; }
        public DateTime change_date { get; set; }

        public virtual toys toy_codeNavigation { get; set; }
    }
}