// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class roles
    {
        public roles()
        {
            users = new HashSet<users>();
        }

        public int role_id { get; set; }
        public string role_name { get; set; }

        public virtual ICollection<users> users { get; set; }
    }
}