// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class users
    {
        public users()
        {
            orders = new HashSet<orders>();
        }

        public int user_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int? role_id { get; set; }
        public bool? state { get; set; }

        public virtual roles role { get; set; }
        public virtual ICollection<orders> orders { get; set; }
    }
}